dbt_mysql:
  target: dev  # Default target
  outputs:  # Target options
    dev:
      driver: MySQL ODBC 8.0 ANSI Driver
      password: "{{ env_var('MARIADB_PASSWORD') }}"
      port: 3306
      schema: hdb_prices_dev
      server: "{{ env_var('MARIADB_HOST') }}"
      type: mariadb
      username: "{{ env_var('MARIADB_USER') }}"
    prod:
      driver: MySQL ODBC 8.0 ANSI Driver
      password: "{{ env_var('MARIADB_PASSWORD') }}"
      port: 3306
      schema: hdb_prices_prod
      server: "{{ env_var('MARIADB_HOST') }}"
      type: mariadb
      username: "{{ env_var('MARIADB_USER') }}"


dbt_elt:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema:
      path: dev.duckdb
      threads: 1

    prod:
      type: duckdb
      schema:
      path: prod.duckdb
      threads: 1


mother_duck:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev_sl
      path: "md:my_db?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 1
      extensions: 
        - httpfs
      settings:
        s3_region: "{{ env_var('REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
    
    prod:
      type: duckdb
      schema: prod
      path:  "md:my_db?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 1
      extensions: 
        - httpfs
      settings:
        s3_region: "{{ env_var('REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"