config-version: 2

name: 'dbt_mysql'
version: "1.0.0"
#require-dbt-version: ">=1.3.0,<2.0.0"
profile: 'dbt_mysql' # This setting configures which "profile" dbt uses for this project.

# File directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Seeds
seeds:
  dbt_mysql:
    +enabled: "{{ target.name != 'prod' }}"
    
# Configuring models
models:
  dbt_mysql:
    # Config indicated by + and applies to all files under its directory
    +full_refresh: true
    staging:
      +materialized: view
    hdb:
      +materialized: table
