version: 2

models:
  - name: stg_sales
    description: "HDB resale records"
    columns:
      - name: sale_id
        description: "Primary Key"
        tests:
          - unique
          - not_null

sources:
  - name: dbt_elt
    description: raw
    schema: hdb_prices_dev
    tables: 
      - name: raw_sales
